/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import dao.ProdutoClicheDAO;
import dao.TrabalhoProdutoClicheDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ProdutoCliche;
import model.TrabalhoProdutoCliche;

/**
 *
 * @author gmg
 */
public class ListarTrabalhos extends javax.swing.JPanel {

    private NovoTrabalho nt;
    private AlterarTrabalho at;

//Metodo Pesquisar Trabalhos
    public void PesquisarTrabalhos() {

        String pesquisa = "%" + txt_pesquisa.getText() + "%";

        TrabalhoProdutoClicheDAO dao = new TrabalhoProdutoClicheDAO();
        List<TrabalhoProdutoCliche> lista = dao.pesquisarTrabalhoProdutoCliche(pesquisa);
        DefaultTableModel dados = (DefaultTableModel) jT_trabalhos.getModel();
        dados.setNumRows(0);
        for (TrabalhoProdutoCliche c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getRp_trabalho(),
                c.getFaca(),
                c.getDestinocliche(),
                c.getTipocliche(),
                c.getId_Cliche(),
                c.getRp_Cliche(),
                c.getCondicao_uso(),
                c.getTrabalho_criado(),
                c.getTrabalho_modificado()
            });

        }

    }

    public ListarTrabalhos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_trabalhos = new javax.swing.JTable();
        btn_novoTrabalho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_pesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jT_trabalhos.setAutoCreateRowSorter(true);
        jT_trabalhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "RP Trabalho", "Faca", "Destino Clichê", "Tipo Clichê", "ID Clichê", "RP Clichê", "Condição de Uso", "Criado", "Modificado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_trabalhos.setFocusable(false);
        jT_trabalhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_trabalhosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_trabalhos);
        if (jT_trabalhos.getColumnModel().getColumnCount() > 0) {
            jT_trabalhos.getColumnModel().getColumn(0).setMinWidth(0);
            jT_trabalhos.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_trabalhos.getColumnModel().getColumn(0).setMaxWidth(0);
            jT_trabalhos.getColumnModel().getColumn(5).setMinWidth(0);
            jT_trabalhos.getColumnModel().getColumn(5).setPreferredWidth(0);
            jT_trabalhos.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        btn_novoTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Adicionar_32px.png"))); // NOI18N
        btn_novoTrabalho.setFocusable(false);
        btn_novoTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoTrabalhoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar_16px.png"))); // NOI18N

        txt_pesquisa.setToolTipText("Pesquisar");
        txt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TRABALHOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_novoTrabalho))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novoTrabalho)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoTrabalhoActionPerformed

        if (nt == null) {
            nt = new NovoTrabalho();
            nt.setLocationRelativeTo(this);
            nt.setVisible(true);
            nt.setTextField();
            nt.PesquisarProdutoCliche();

        }
        nt.setVisible(true);
        nt.setTextField();
        nt.PesquisarProdutoCliche();

    }//GEN-LAST:event_btn_novoTrabalhoActionPerformed

    private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisaKeyReleased

        PesquisarTrabalhos();

    }//GEN-LAST:event_txt_pesquisaKeyReleased

    private void jT_trabalhosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_trabalhosMouseClicked

        jT_trabalhos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {

                    if (at == null) {
                        at = new AlterarTrabalho();

                        int x = jT_trabalhos.getLocationOnScreen().x + (jT_trabalhos.getWidth() - at.getWidth()) / 2;
                        int y = jT_trabalhos.getLocation().y + (at.getHeight() / 2);

                        at.setLocation(x, y);

                        at.AtualizarId(jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 0).toString());
                        at.AtualizarRptrabalho(jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 1).toString());
                        at.AtualizarIdCliche((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 5).toString()));
                        at.Atualizarpesquisa((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 6).toString()));
                        at.AtualizarCondicaoUso((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 7).toString()));
                        at.AtualizarData((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 8).toString()));
                        at.PesquisarProdutoCliche();
                        at.setVisible(true);

                    }
                    at.AtualizarId(jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 0).toString());
                    at.AtualizarRptrabalho(jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 1).toString());
                    at.AtualizarIdCliche((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 5).toString()));
                    at.Atualizarpesquisa((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 6).toString()));
                    at.AtualizarCondicaoUso((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 7).toString()));
                    at.AtualizarData((jT_trabalhos.getValueAt(jT_trabalhos.getSelectedRow(), 8).toString()));
                    at.PesquisarProdutoCliche();
                    at.setVisible(true);

                }
            }

        });

    }//GEN-LAST:event_jT_trabalhosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_novoTrabalho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_trabalhos;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
