package form;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author gmg
 */
public class Principal extends javax.swing.JFrame {

    private GerenciarClientes gc = null;
    private GerenciarTipoCliche gtc = null;
    private GerenciarDestinoCliche gdc = null;

//Metodo mostrar cardLayout do jP_CardLayout
    public void MostraCardLayout(String card) {
        CardLayout cl = (CardLayout) jP_CardLayout.getLayout();
        cl.show(jP_CardLayout, card);
    }

    public Principal() {
        initComponents();
        setIconImage();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jP_CardLayout = new javax.swing.JPanel();
        jP_ListarCliche = new javax.swing.JPanel();
        listarCliches1 = new form.ListarCliches();
        jP_ListarTrabalhos = new javax.swing.JPanel();
        listarTrabalhos1 = new form.ListarTrabalhos();
        jP_infoGeral = new javax.swing.JPanel();
        infoGeral1 = new form.InfoGeral();
        jP_EliminarCliche = new javax.swing.JPanel();
        eliminarCliches1 = new form.EliminarCliches();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlexoApp");
        setMinimumSize(new java.awt.Dimension(1200, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CartonDruck 3D.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton1.setText("Clichês");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton2.setText("Trabalhos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton3.setText("Informação Geral");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton5.setText("Eliminar Clichês");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton6.setText("Gerenciar Clientes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton7.setText("Gerenciar Tipo Clichê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton8.setText("Gerenciar Destino Clichê");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(25, 25, 25)
                .addComponent(jButton2)
                .addGap(25, 25, 25)
                .addComponent(jButton3)
                .addGap(25, 25, 25)
                .addComponent(jButton5)
                .addGap(60, 60, 60)
                .addComponent(jButton6)
                .addGap(25, 25, 25)
                .addComponent(jButton7)
                .addGap(25, 25, 25)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_CardLayout.setBackground(new java.awt.Color(255, 0, 204));
        jP_CardLayout.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jP_ListarClicheLayout = new javax.swing.GroupLayout(jP_ListarCliche);
        jP_ListarCliche.setLayout(jP_ListarClicheLayout);
        jP_ListarClicheLayout.setHorizontalGroup(
            jP_ListarClicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarCliches1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jP_ListarClicheLayout.setVerticalGroup(
            jP_ListarClicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarCliches1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        jP_CardLayout.add(jP_ListarCliche, "ListarCliche");
        jP_ListarCliche.getAccessibleContext().setAccessibleName("ListarCliche");

        javax.swing.GroupLayout jP_ListarTrabalhosLayout = new javax.swing.GroupLayout(jP_ListarTrabalhos);
        jP_ListarTrabalhos.setLayout(jP_ListarTrabalhosLayout);
        jP_ListarTrabalhosLayout.setHorizontalGroup(
            jP_ListarTrabalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarTrabalhos1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jP_ListarTrabalhosLayout.setVerticalGroup(
            jP_ListarTrabalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarTrabalhos1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        jP_CardLayout.add(jP_ListarTrabalhos, "ListarTrabalhos");
        jP_ListarTrabalhos.getAccessibleContext().setAccessibleName("ListarTrabalhos");

        javax.swing.GroupLayout jP_infoGeralLayout = new javax.swing.GroupLayout(jP_infoGeral);
        jP_infoGeral.setLayout(jP_infoGeralLayout);
        jP_infoGeralLayout.setHorizontalGroup(
            jP_infoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoGeral1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jP_infoGeralLayout.setVerticalGroup(
            jP_infoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoGeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, Short.MAX_VALUE)
        );

        jP_CardLayout.add(jP_infoGeral, "infoGeral");
        jP_infoGeral.getAccessibleContext().setAccessibleName("infoGeral");

        javax.swing.GroupLayout jP_EliminarClicheLayout = new javax.swing.GroupLayout(jP_EliminarCliche);
        jP_EliminarCliche.setLayout(jP_EliminarClicheLayout);
        jP_EliminarClicheLayout.setHorizontalGroup(
            jP_EliminarClicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarCliches1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jP_EliminarClicheLayout.setVerticalGroup(
            jP_EliminarClicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarCliches1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        jP_CardLayout.add(jP_EliminarCliche, "EliminarCliche");
        jP_EliminarCliche.getAccessibleContext().setAccessibleName("EliminarCliche");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_CardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_CardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        MostraCardLayout("ListarCliche");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        MostraCardLayout("ListarTrabalhos");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MostraCardLayout("infoGeral");
        infoGeral1.ContaClichesparaEliminar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        MostraCardLayout("EliminarCliche");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (gc == null) {
            gc = new GerenciarClientes();
            gc.setLocationRelativeTo(this);
            gc.setVisible(true);
        }
        gc.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (gtc == null) {
            gtc = new GerenciarTipoCliche();
            gtc.setLocationRelativeTo(this);
            gtc.setVisible(true);
        }
        gtc.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if (gdc == null) {
            gdc = new GerenciarDestinoCliche();
            gdc.setLocationRelativeTo(this);
            gdc.setVisible(true);
        }
        gdc.setVisible(true);


    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        listarCliches1.PesquisarCliche();
        listarTrabalhos1.PesquisarTrabalhos();
        infoGeral1.listarCbDestinoCliche();
        infoGeral1.listarCbTipoCliche();
        infoGeral1.AtualizarAnosCliches();
        infoGeral1.ContarClichesNovos();
        infoGeral1.ResetInfoEliminar();

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_64px.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private form.EliminarCliches eliminarCliches1;
    private form.InfoGeral infoGeral1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_CardLayout;
    private javax.swing.JPanel jP_EliminarCliche;
    private javax.swing.JPanel jP_ListarCliche;
    private javax.swing.JPanel jP_ListarTrabalhos;
    private javax.swing.JPanel jP_infoGeral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private form.ListarCliches listarCliches1;
    private form.ListarTrabalhos listarTrabalhos1;
    // End of variables declaration//GEN-END:variables
}
