/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flexoapp.form;

import flexoapp.dao.ClienteDAO;
import flexoapp.dao.TipoClicheDAO;
import flexoapp.model.Cliente;
import flexoapp.model.TipoCliche;
import flexoapp.model.Utilitarios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gmg
 */
public class GerenciarTipoCliche extends javax.swing.JFrame {

//Metodo listar TipoCliche
    public void listarTipoCliche() {
        TipoClicheDAO dao = new TipoClicheDAO();
        List<TipoCliche> lista = dao.listarTipoCliche();
        DefaultTableModel dados = (DefaultTableModel) jT_tipoCliche.getModel();
        dados.setNumRows(0);
        for (TipoCliche c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCriado(),
                c.getModificado()});
        }
    }

    public GerenciarTipoCliche() {
        initComponents();
        this.setResizable(false);
        listarTipoCliche();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_limparTipoCliche = new javax.swing.JButton();
        btn_excluirTipoCliche = new javax.swing.JButton();
        btn_alterarTipoCliche = new javax.swing.JButton();
        btn_novoTipoCliche = new javax.swing.JButton();
        txt_nomeTipoCliche = new javax.swing.JTextField();
        txt_idTipoCliche = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_tipoCliche = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Tipo Clichê");
        setMinimumSize(new java.awt.Dimension(450, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btn_limparTipoCliche.setBackground(new java.awt.Color(22, 22, 22));
        btn_limparTipoCliche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flexoapp/img/Limpar_32px.png"))); // NOI18N
        btn_limparTipoCliche.setToolTipText("Limpar!");
        btn_limparTipoCliche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_limparTipoCliche.setBorderPainted(false);
        btn_limparTipoCliche.setEnabled(false);
        btn_limparTipoCliche.setMaximumSize(new java.awt.Dimension(40, 40));
        btn_limparTipoCliche.setMinimumSize(new java.awt.Dimension(40, 40));
        btn_limparTipoCliche.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_limparTipoCliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparTipoClicheActionPerformed(evt);
            }
        });

        btn_excluirTipoCliche.setBackground(new java.awt.Color(22, 22, 22));
        btn_excluirTipoCliche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flexoapp/img/Remover_32px.png"))); // NOI18N
        btn_excluirTipoCliche.setToolTipText("Excluir!");
        btn_excluirTipoCliche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_excluirTipoCliche.setBorderPainted(false);
        btn_excluirTipoCliche.setEnabled(false);
        btn_excluirTipoCliche.setMaximumSize(new java.awt.Dimension(40, 40));
        btn_excluirTipoCliche.setMinimumSize(new java.awt.Dimension(40, 40));
        btn_excluirTipoCliche.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_excluirTipoCliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirTipoClicheActionPerformed(evt);
            }
        });

        btn_alterarTipoCliche.setBackground(new java.awt.Color(22, 22, 22));
        btn_alterarTipoCliche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flexoapp/img/Alterar_32px.png"))); // NOI18N
        btn_alterarTipoCliche.setToolTipText("Alterar!");
        btn_alterarTipoCliche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_alterarTipoCliche.setBorderPainted(false);
        btn_alterarTipoCliche.setEnabled(false);
        btn_alterarTipoCliche.setMaximumSize(new java.awt.Dimension(40, 40));
        btn_alterarTipoCliche.setMinimumSize(new java.awt.Dimension(40, 40));
        btn_alterarTipoCliche.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_alterarTipoCliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarTipoClicheActionPerformed(evt);
            }
        });

        btn_novoTipoCliche.setBackground(new java.awt.Color(22, 22, 22));
        btn_novoTipoCliche.setForeground(new java.awt.Color(255, 255, 255));
        btn_novoTipoCliche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flexoapp/img/Adicionar_32px.png"))); // NOI18N
        btn_novoTipoCliche.setToolTipText("Adicionar novo!");
        btn_novoTipoCliche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_novoTipoCliche.setBorderPainted(false);
        btn_novoTipoCliche.setEnabled(false);
        btn_novoTipoCliche.setMaximumSize(new java.awt.Dimension(40, 40));
        btn_novoTipoCliche.setMinimumSize(new java.awt.Dimension(40, 40));
        btn_novoTipoCliche.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_novoTipoCliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoTipoClicheActionPerformed(evt);
            }
        });

        txt_nomeTipoCliche.setBackground(new java.awt.Color(63, 63, 63));
        txt_nomeTipoCliche.setForeground(new java.awt.Color(255, 255, 255));
        txt_nomeTipoCliche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nomeTipoCliche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomeTipoClicheKeyPressed(evt);
            }
        });

        txt_idTipoCliche.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_idTipoCliche.setForeground(new java.awt.Color(63, 63, 63));
        txt_idTipoCliche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idTipoCliche.setBorder(null);
        txt_idTipoCliche.setEnabled(false);
        txt_idTipoCliche.setFocusable(false);
        txt_idTipoCliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idTipoClicheActionPerformed(evt);
            }
        });

        jT_tipoCliche.setAutoCreateRowSorter(true);
        jT_tipoCliche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nome", "Criado", "Modificado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_tipoCliche.setToolTipText("Duplo clicke no registro para alterá-lo!");
        jT_tipoCliche.setFocusable(false);
        jT_tipoCliche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_tipoClicheMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_tipoCliche);
        if (jT_tipoCliche.getColumnModel().getColumnCount() > 0) {
            jT_tipoCliche.getColumnModel().getColumn(0).setMinWidth(0);
            jT_tipoCliche.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_tipoCliche.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_idTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomeTipoCliche)
                        .addGap(18, 18, 18)
                        .addComponent(btn_novoTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterarTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluirTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limparTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_alterarTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluirTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limparTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novoTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nomeTipoCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limparTipoClicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparTipoClicheActionPerformed

        txt_idTipoCliche.setText("");
        txt_nomeTipoCliche.setText("");

        btn_novoTipoCliche.setEnabled(false);
        btn_alterarTipoCliche.setEnabled(false);
        btn_excluirTipoCliche.setEnabled(false);
        btn_limparTipoCliche.setEnabled(false);
    }//GEN-LAST:event_btn_limparTipoClicheActionPerformed

    private void btn_excluirTipoClicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirTipoClicheActionPerformed
        // botao Excluir Clientes
        TipoCliche obj = new TipoCliche();

        obj.setId(Integer.parseInt(txt_idTipoCliche.getText()));

        TipoClicheDAO dao = new TipoClicheDAO();

        dao.excluirTipoCliche(obj);

        //Limpa os paineis
        txt_idTipoCliche.setText("");
        txt_nomeTipoCliche.setText("");

        //desabilita botões
        btn_novoTipoCliche.setEnabled(false);
        btn_alterarTipoCliche.setEnabled(false);
        btn_excluirTipoCliche.setEnabled(false);
        btn_limparTipoCliche.setEnabled(false);

        //AtualizarcbClientes();
    }//GEN-LAST:event_btn_excluirTipoClicheActionPerformed

    private void btn_alterarTipoClicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarTipoClicheActionPerformed
        // Alterar novo registro Cliente
        Utilitarios dh = new Utilitarios();
        String dataHora = dh.DH();

        TipoCliche obj = new TipoCliche();

        obj.setNome(txt_nomeTipoCliche.getText());
        obj.setCriado(jT_tipoCliche.getValueAt(jT_tipoCliche.getSelectedRow(), 2).toString());
        obj.setModificado(dataHora);
        obj.setId(Integer.parseInt(txt_idTipoCliche.getText()));

        TipoClicheDAO dao = new TipoClicheDAO();
        dao.alterarTipoCliche(obj);

        txt_idTipoCliche.setText("");
        txt_nomeTipoCliche.setText("");

        btn_novoTipoCliche.setEnabled(false);
        btn_alterarTipoCliche.setEnabled(false);
        btn_excluirTipoCliche.setEnabled(false);
        btn_limparTipoCliche.setEnabled(false);

        //AtualizarcbClientes();
    }//GEN-LAST:event_btn_alterarTipoClicheActionPerformed

    private void btn_novoTipoClicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoTipoClicheActionPerformed
        // Criar novo registro Cliente
        Utilitarios dh = new Utilitarios();
        String dataHora = dh.DH();

        TipoCliche obj = new TipoCliche();

        obj.setNome(txt_nomeTipoCliche.getText());
        obj.setCriado(dataHora);
        obj.setModificado(dataHora);

        TipoClicheDAO dao = new TipoClicheDAO();
        dao.CadastrarTipoCliche(obj);

        txt_idTipoCliche.setText("");
        txt_nomeTipoCliche.setText("");

        btn_novoTipoCliche.setEnabled(false);
        btn_alterarTipoCliche.setEnabled(false);
        btn_excluirTipoCliche.setEnabled(false);
        btn_limparTipoCliche.setEnabled(false);

        //AtualizarcbClientes();
    }//GEN-LAST:event_btn_novoTipoClicheActionPerformed

    private void txt_nomeTipoClicheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeTipoClicheKeyPressed
        if ("".equals(txt_idTipoCliche.getText())) {
            btn_novoTipoCliche.setEnabled(true);
            btn_alterarTipoCliche.setEnabled(false);
            btn_excluirTipoCliche.setEnabled(false);
            btn_limparTipoCliche.setEnabled(true);
        }
    }//GEN-LAST:event_txt_nomeTipoClicheKeyPressed

    private void txt_idTipoClicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idTipoClicheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idTipoClicheActionPerformed

    private void jT_tipoClicheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_tipoClicheMouseClicked

        jT_tipoCliche.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    txt_idTipoCliche.setText(jT_tipoCliche.getValueAt(jT_tipoCliche.getSelectedRow(), 0).toString());
                    txt_nomeTipoCliche.setText(jT_tipoCliche.getValueAt(jT_tipoCliche.getSelectedRow(), 1).toString());

                    //desabilita botões
                    btn_novoTipoCliche.setEnabled(false);
                    btn_alterarTipoCliche.setEnabled(true);
                    btn_excluirTipoCliche.setEnabled(true);
                    btn_limparTipoCliche.setEnabled(true);

                }
            }
        });
    }//GEN-LAST:event_jT_tipoClicheMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTipoCliche();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarTipoCliche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarTipoCliche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarTipoCliche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarTipoCliche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarTipoCliche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterarTipoCliche;
    private javax.swing.JButton btn_excluirTipoCliche;
    private javax.swing.JButton btn_limparTipoCliche;
    private javax.swing.JButton btn_novoTipoCliche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_tipoCliche;
    private javax.swing.JTextField txt_idTipoCliche;
    private javax.swing.JTextField txt_nomeTipoCliche;
    // End of variables declaration//GEN-END:variables
}
