/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package flexoapp.form;

import flexoapp.dao.ProdutoClicheDAO;
import flexoapp.model.ProdutoCliche;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gmg
 */
public class ListarCliches extends javax.swing.JPanel {

    private NovoCliche nc;

//Metodo listar FilmeFaca
    public void listarCliche() {
        ProdutoClicheDAO dao = new ProdutoClicheDAO();
        List<ProdutoCliche> lista = dao.ProdutoCliche();
        DefaultTableModel dados = (DefaultTableModel) jt_cliches.getModel();
        dados.setNumRows(0);
        for (ProdutoCliche c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getRp_cliche(),
                c.getFaca(),
                c.getFt(),
                c.getCliente_id(),
                c.getTipoCliche_id(),
                c.getDestinoCliche_id(),
                c.getStatus(),
                c.getCliche_criado(),
                c.getCliche_modificado()
            });
        }
    }

    public ListarCliches() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cliches = new javax.swing.JTable();
        jl_totalCliche = new javax.swing.JLabel();
        btn_novoCliche = new javax.swing.JButton();
        txt_pesquisaCliche = new javax.swing.JTextField();
        jl_totalCliche1 = new javax.swing.JLabel();

        jt_cliches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "RP Cliche", "Faca", "FT", "Cliente", "Tipo Cliche", "Destino", "Status", "Criado", "Modificado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_cliches.setFocusable(false);
        jScrollPane1.setViewportView(jt_cliches);
        if (jt_cliches.getColumnModel().getColumnCount() > 0) {
            jt_cliches.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jl_totalCliche.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_totalCliche.setText("Clichês");

        btn_novoCliche.setText("Novo Clichê");
        btn_novoCliche.setFocusable(false);
        btn_novoCliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoClicheActionPerformed(evt);
            }
        });

        txt_pesquisaCliche.setToolTipText("Busca");

        jl_totalCliche1.setText("Total: 10000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_pesquisaCliche, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_novoCliche))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_totalCliche1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_totalCliche, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novoCliche)
                    .addComponent(txt_pesquisaCliche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_totalCliche)
                    .addComponent(jl_totalCliche1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoClicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoClicheActionPerformed

        if (nc == null) {
            nc = new NovoCliche();
            nc.setLocationRelativeTo(this);
            nc.setVisible(true);
        }
        nc.setVisible(true);
    }//GEN-LAST:event_btn_novoClicheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_novoCliche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_totalCliche;
    private javax.swing.JLabel jl_totalCliche1;
    private javax.swing.JTable jt_cliches;
    private javax.swing.JTextField txt_pesquisaCliche;
    // End of variables declaration//GEN-END:variables
}
